config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :hashtag_events
  resources :hashtags
  resources :events
  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

   root 'welcome#index'

end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  has_many :hashtag_events

  validates :name, presence: true, uniqueness: true  

end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  before_action :set_hashtag, only: [:show, :edit, :update, :destroy]

  # GET /hashtags
  # GET /hashtags.json
  def index
    @hashtags = Hashtag.all
  end

  # GET /hashtags/1
  # GET /hashtags/1.json
  def show
  end

  # GET /hashtags/new
  def new
    @hashtag = Hashtag.new
  end

  # GET /hashtags/1/edit
  def edit
  end

  # POST /hashtags
  # POST /hashtags.json
  def create
    @hashtag = Hashtag.new(hashtag_params)

    respond_to do |format|
      if @hashtag.save
        format.html { redirect_to @hashtag, notice: 'Hashtag was successfully created.' }
        format.json { render :show, status: :created, location: @hashtag }
      else
        format.html { render :new }
        format.json { render json: @hashtag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hashtags/1
  # PATCH/PUT /hashtags/1.json
  def update
    respond_to do |format|
      if @hashtag.update(hashtag_params)
        format.html { redirect_to @hashtag, notice: 'Hashtag was successfully updated.' }
        format.json { render :show, status: :ok, location: @hashtag }
      else
        format.html { render :edit }
        format.json { render json: @hashtag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hashtags/1
  # DELETE /hashtags/1.json
  def destroy
    @hashtag.destroy
    respond_to do |format|
      format.html { redirect_to hashtags_url, notice: 'Hashtag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hashtag
      @hashtag = Hashtag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hashtag_params
      params.require(:hashtag).permit(:name)
    end
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/views/hashtags/_form.html.haml
= form_for @hashtag do |f|
  - if @hashtag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@hashtag.errors.count, "error")} prohibited this hashtag from being saved:"
      %ul
        - @hashtag.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/hashtags/edit.html.haml
%h1 Editing hashtag

= render 'form'

= link_to 'Show', @hashtag
\|
= link_to 'Back', hashtags_path

app/views/hashtags/index.html.haml
%h1 Listing hashtags

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @hashtags.each do |hashtag|
      %tr
        %td= hashtag.name
        %td= link_to 'Show', hashtag
        %td= link_to 'Edit', edit_hashtag_path(hashtag)
        %td= link_to 'Destroy', hashtag, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Hashtag', new_hashtag_path

app/views/hashtags/new.html.haml
%h1 New hashtag

= render 'form'

= link_to 'Back', hashtags_path

app/views/hashtags/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @hashtag.name

= link_to 'Edit', edit_hashtag_path(@hashtag)
\|
= link_to 'Back', hashtags_path