config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :hashtag_events
  resources :hashtags
  resources :events
  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

   root 'welcome#index'

end

app/models/hashtag_event.rb
class HashtagEvent < ActiveRecord::Base
  belongs_to :hashtag
  belongs_to :event

  validates :hashtag_id, presence: true, uniqueness: {scope: :event_id}
  validates :event_id, presence: true  
end

app/controllers/hashtag_events_controller.rb
class HashtagEventsController < ApplicationController
  before_action :set_hashtag_event, only: [:show, :edit, :update, :destroy]

  # GET /hashtag_events
  # GET /hashtag_events.json
  def index
    @hashtag_events = HashtagEvent.all
  end

  # GET /hashtag_events/1
  # GET /hashtag_events/1.json
  def show
  end

  # GET /hashtag_events/new
  def new
    @hashtag_event = HashtagEvent.new
  end

  # GET /hashtag_events/1/edit
  def edit
  end

  # POST /hashtag_events
  # POST /hashtag_events.json
  def create
    @hashtag_event = HashtagEvent.new(hashtag_event_params)

    respond_to do |format|
      if @hashtag_event.save
        format.html { redirect_to @hashtag_event, notice: 'Hashtag event was successfully created.' }
        format.json { render :show, status: :created, location: @hashtag_event }
      else
        format.html { render :new }
        format.json { render json: @hashtag_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hashtag_events/1
  # PATCH/PUT /hashtag_events/1.json
  def update
    respond_to do |format|
      if @hashtag_event.update(hashtag_event_params)
        format.html { redirect_to @hashtag_event, notice: 'Hashtag event was successfully updated.' }
        format.json { render :show, status: :ok, location: @hashtag_event }
      else
        format.html { render :edit }
        format.json { render json: @hashtag_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hashtag_events/1
  # DELETE /hashtag_events/1.json
  def destroy
    @hashtag_event.destroy
    respond_to do |format|
      format.html { redirect_to hashtag_events_url, notice: 'Hashtag event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hashtag_event
      @hashtag_event = HashtagEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hashtag_event_params
      params.require(:hashtag_event).permit(:hashtag_id, :event_id)
    end
end

app/helpers/hashtag_events_helper.rb
module HashtagEventsHelper
  def event_options(selected)
    options_for_select(Event.all.map { |event| ["#{event.name}", event.id] }, selected)
  end

  def hashtag_options(selected)
    options_for_select(Hashtag.all.map { |hashtag| ["#{hashtag.name}", hashtag.id] }, selected)
  end
end

app/views/hashtag_events/_form.html.haml
= form_for @hashtag_event do |f|
  - if @hashtag_event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@hashtag_event.errors.count, "error")} prohibited this hashtag_event from being saved:"
      %ul
        - @hashtag_event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :hashtag
    = f.select(:hashtag_id, hashtag_options(f.object.hashtag_id))
  .field
    = f.label :event
    = f.select(:event_id, event_options(f.object.event_id))
  .actions
    = f.submit 'Save'

app/views/hashtag_events/edit.html.haml
%h1 Editing hashtag_event

= render 'form'

= link_to 'Show', @hashtag_event
\|
= link_to 'Back', hashtag_events_path

app/views/hashtag_events/index.html.haml
%h1 Listing hashtag_events

%table
  %thead
    %tr
      %th Hashtag
      %th Event
      %th
      %th
      %th

  %tbody
    - @hashtag_events.each do |hashtag_event|
      %tr
        %td= hashtag_event.hashtag.name
        %td= hashtag_event.event.name
        %td= link_to 'Show', hashtag_event
        %td= link_to 'Edit', edit_hashtag_event_path(hashtag_event)
        %td= link_to 'Destroy', hashtag_event, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Hashtag event', new_hashtag_event_path

app/views/hashtag_events/new.html.haml
%h1 New hashtag_event

= render 'form'

= link_to 'Back', hashtag_events_path

app/views/hashtag_events/show.html.haml
%p#notice= notice

%p
  %b Hashtag:
  = @hashtag_event.hashtag.name
%p
  %b Event:
  = @hashtag_event.event.name

= link_to 'Edit', edit_hashtag_event_path(@hashtag_event)
\|
= link_to 'Back', hashtag_events_path